### PR TITLE
README.md new instructions JSON + bash scripts

### LINKED ISSUE #8: Provide output from module
after apply, it would be nice to have an overview with hostnames and addresses. figure out a way how to provide that by default.

### PR DESCRIPTION
**Pull request by smartbit**
GCE changed the way to [get a JSON-file](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork). Mostly a text copy from [Authentication JSON File](https://www.terraform.io/docs/providers/google/index.html). 

Extra bash scripts that eases manual testing. Partially fixes #8. Requires PR #45.

### CODE REVIEW

**Comment by frankscholten** [comment]
Thanks @smartbit! Can you merge master back in? I'll merge it.

**Comment by smartbit** [comment]
Away from computer till Sunday 31th, will do upon return. Hope it can wait.

**Comment by frankscholten** [comment]
No problem

**Comment by smartbit** [comment]
Merged back master. Got no conflicts with the base branch.

**Pull request merged**
